package es.jesmon.entities;
// Generated 29-ene-2018 22:17:55 by Hibernate Tools 5.2.6.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.apache.commons.lang.StringUtils;

/**
 * Tramitador generated by hbm2java
 */
@Entity
@Table(name = "grupo", catalog = "jesmon")
public class Grupo  implements java.io.Serializable {

	private static final long serialVersionUID = 6933726978664517149L;
	private Integer idGrupo;
	private int genero;
	private int numpersonas;
	private int edad;
	private byte[] foto;
	private String intereses;
	
	
	
	public Grupo() {
	}
	
	public Grupo(Integer idGrupo) {
		this.idGrupo = idGrupo;
	}

	public Grupo(int genero, int numpersonas, int edad, String intereses) {
		this.genero = genero;
		this.numpersonas = numpersonas;
		this.edad = edad;
		this.intereses = intereses;
	}

	

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_grupo", unique = true, nullable = false)
	public Integer getIdGrupo() {
		return this.idGrupo;
	}

	public void setIdGrupo(Integer idGrupo) {
		this.idGrupo = idGrupo;
	}
	

	@Column(name = "genero", nullable = false, length = 11)
	public int getGenero() {
		return this.genero;
	}

	public void setGenero(int genero) {
		this.genero = genero;
	}

	@Column(name = "numpersonas", nullable = false, length = 11)
	public int getnumpersonas() {
		return this.numpersonas;
	}

	public void setnumpersonas(int numpersonas) {
		this.numpersonas = numpersonas;
	}

	@Column(name = "edad", length = 11)
	public int getEdad() {
		return this.edad;
	}

	public void setEdad(int edad) {
		this.edad = edad;
	}

	@Column(name = "intereses", length = 1000)
	public String getIntereses() {
		return this.intereses;
	}

	public void setIntereses(String intereses) {
		this.intereses = intereses;
	}

	@Column(name = "foto")
	public byte[] getFoto() {
		return this.foto;
	}

	public void setFoto(byte[] foto) {
		this.foto = foto;
	}

	
	
	public boolean equals(Object o) {
		if(o == null || !o.getClass().equals(Grupo.class))
			return false;

		Grupo grupo = (Grupo)o;
		return idGrupo.equals(grupo.getIdGrupo());
	}

	
}
