package es.jesmon.entities;
// Generated 29-ene-2018 22:17:55 by Hibernate Tools 5.2.6.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.apache.commons.lang.StringUtils;

/**
 * Tramitador generated by hbm2java
 */
@Entity
@Table(name = "tramitador", catalog = "jesmon")
public class Tramitador extends JesmonEntity implements java.io.Serializable {

	private static final long serialVersionUID = 6933726978664517149L;
	private Integer idTramitador;
	private String nif;
	private String nombre;
//	private String apellido1;
//	private String apellido2;
	private String email;
	private String telefono;
	private int activo;
	public int getActivo() {
		return activo;
	}

	public void setActivo(int activo) {
		this.activo = activo;
	}

	private byte[] password;
	private String login;
    private Grupo grupo; 
    
    
    @ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_grupo", nullable = false)
	public Grupo getGrupo() {
		return grupo;
	}

	public void setGrupo(Grupo grupo) {
		this.grupo = grupo;
	}

	public Tramitador() {
	}

	public Tramitador(String nif, String nombre) {
		this.nif = nif;
		this.nombre = nombre;
	}

	public Tramitador(String nif, String nombre,  String email, byte[] password, String login) {
		this.nif = nif;
		this.nombre = nombre;
//		this.apellido1 = apellido1;
//		this.apellido2 = apellido2;
		this.email = email;
		this.telefono = telefono;
		
		this.password = password;
		this.login = login;
//		this.mensajes = mensajes;
//		this.incidencias = incidencias;
//		this.estadoIncidencias = estadoIncidencias;
//		this.sedes = sedes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_tramitador", unique = true, nullable = false)
	public Integer getIdTramitador() {
		return this.idTramitador;
	}

	public void setIdTramitador(Integer idTramitador) {
		this.idTramitador = idTramitador;
	}

	@Column(name = "NIF", nullable = false, length = 9)
	public String getNif() {
		return this.nif;
	}

	public void setNif(String nif) {
		this.nif = nif;
	}

	@Column(name = "nombre", nullable = false, length = 100)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}





	@Column(name = "email", length = 50)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	


	@Column(name = "password")
	public byte[] getPassword() {
		return this.password;
	}

	public void setPassword(byte[] password) {
		this.password = password;
	}



	@Transient
	public String getNombreCompleto() {
		String nombreCompleto = "";
		if(StringUtils.isNotBlank(nombre))
			nombreCompleto = nombre;
//		if(StringUtils.isNotBlank(apellido1))
//			nombreCompleto += " " + apellido1;
//		if(StringUtils.isNotBlank(apellido2))
//			nombreCompleto += " " + apellido2;
		return nombreCompleto.trim();
	}
	
	@Transient
	public Integer getId() {
		return idTramitador;
	}
	
	@Transient
	public String getNombreCampoId() {
		return "idTramitador";
	}
	
	@Column(name = "login", length = 50)
	public String getLogin() {
		return login;
	}
	public void setLogin(String login) {
		this.login = login;
	}
	
	public boolean equals(Object o) {
		if(o == null || !o.getClass().equals(Tramitador.class))
			return false;

		Tramitador tramitador = (Tramitador)o;
		return idTramitador.equals(tramitador.getIdTramitador());
	}
}
